config/routes.rb
Testgmaps::Application.routes.draw do

	 root to: 'gadds#index'

  resources :gadds

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/gadd.rb
# == Schema Information
#
# Table name: gadds
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  latitude   :float
#  longitude  :float
#  gmaps      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  gmaps_zoom :float
#  privacy    :string(255)
#

class Gadd < ActiveRecord::Base
	attr_accessible :latitude, :longitude, :name, :gmaps_zoom, :privacy


	PRIVACY_SETTINGS = ['Public', 'Intimate', 'Secret']

	#belongs_to :user

	validates :name, :length => {:maximum => 140},
		uniqueness: { case_sensitive: false },
		presence: true

	validates :latitude, presence: true
	validates :longitude, presence: true
	validates :privacy, presence: true

	acts_as_gmappable :latitude => 'lat', :longitude => 'lng'

	def gmaps4rails_address
	#describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki

	end

	def gmaps4rails_infowindow
		"<h1>#{name}</h1>"
	end

	def gmaps4rails_marker_picture
	{
		"picture" => "/images/gmap_marker.png",          # string,  mandatory
		"width" => "20" ,          # integer, mandatory
		"height" => "34",          # integer, mandatory

		# See doc here: http://google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/docs/reference.html
	}
	end





	def self.search(search)
		if search
			find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
		else
			find(:all)
		end
	end





end

app/models/privacy.rb
# == Schema Information
#
# Table name: privacies
#
#  id         :integer          not null, primary key
#  type       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Privacy < ActiveRecord::Base
  attr_accessible :type
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base

	attr_accessible :name, :email, :password, :password_confirmation
	has_secure_password

	before_save { self.email.downcase! }
	before_save :create_remember_token

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:   true,
				        format:     { with: VALID_EMAIL_REGEX },
				        uniqueness: { case_sensitive: false }
	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gadds_controller.rb
class GaddsController < ApplicationController
  # GET /gadds
  # GET /gadds.json





  def index
    @gadds = Gadd.search(params[:search])
	 @json = Gadd.search(params[:search]).to_gmaps4rails

		#test, pour inclure la possibilité de se creer une geoad dans index, ca prend la variable:
		@gadd = Gadd.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gadds }
    end
  end

  # GET /gadds/1
  # GET /gadds/1.json
  def show
    @gadd = Gadd.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gadd }
    end
  end

  # GET /gadds/new
  # GET /gadds/new.json
  def new
    @gadd = Gadd.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gadd }
    end
  end

  # GET /gadds/1/edit
  def edit
    @gadd = Gadd.find(params[:id])
  end

  # POST /gadds
  # POST /gadds.json
  def create
    @gadd = Gadd.new(params[:gadd])
	 @gadd.gmaps = true
    respond_to do |format|
      if @gadd.save
        format.html { redirect_to @gadd, notice: 'Gadd was successfully created.' }
        format.json { render json: @gadd, status: :created, location: @gadd }
      else
        format.html { render action: "new" }
        format.json { render json: @gadd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gadds/1
  # PUT /gadds/1.json
  def update
    @gadd = Gadd.find(params[:id])

    respond_to do |format|
      if @gadd.update_attributes(params[:gadd])
        format.html { redirect_to @gadd, notice: 'Gadd was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gadd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gadds/1
  # DELETE /gadds/1.json
  def destroy
    @gadd = Gadd.find(params[:id])
    @gadd.destroy

    respond_to do |format|
      format.html { redirect_to gadds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end


  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadds_helper.rb
module GaddsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

	def current_user=(user)
    @current_user = user
  end

	def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gadds/_form.html.erb
<%= form_for(@gadd) do |f| %>
  <% if @gadd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gadd.errors.count, "error") %> prohibited this gadd from being saved:</h2>

      <ul>
      <% @gadd.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<br />

  <table>
  <tr>
    <th><%= f.label :name %></th>
    <th><%= f.label :latitude %></th>
    <th><%= f.label :longitude %></th>
    <th><%= f.label :gmaps_zoom %></th>
  </tr>

  <tr>
    <th><%= f.text_field :name %></th>
    <th><%= f.text_field :latitude %></th>
    <th><%= f.text_field :longitude %></th>
    <th><%= f.text_field :gmaps_zoom %></th>
  </tr>

	</table>



	<br/>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/gadds/_form_create_gadd.html.erb
<%= simple_form_for(@gadd) do |f| %>
	<%= f.input :name %>
	<%= f.input :latitude, :as => :hidden %>
	<%= f.input :longitude, :as => :hidden %>
	<%= f.input :gmaps_zoom, :as => :hidden %>
	<%= f.input :privacy, collection: ['Public', 'Friends', 'Secret'], as: :radio_buttons  %>
	<%= f.button :submit %>

<% end %>

app/views/gadds/_gmaps4rails_new.html.erb
    <% content_for :scripts do %>
    <script type="text/javascript" charset="utf-8">
        var markersArray = [];
        // On click, clear markers, place a new one, update coordinates in the form
        Gmaps.map.callback = function() {
            google.maps.event.addListener(Gmaps.map.serviceObject, 'click', function(event) {
              clearOverlays();
              placeMarker(event.latLng);
              updateFormLocation(event.latLng);
            });
        };
        // Update form attributes with given coordinates
        function updateFormLocation(latLng) {
            $('#gadd_latitude').val(latLng.lat());
            $('#gadd_longitude').val(latLng.lng());
            $('#gadd_gmaps_zoom').val(Gmaps.map.serviceObject.getZoom());
        }
        // Add a marker with an open infowindow
        function placeMarker(latLng) {
            var marker = new google.maps.Marker({
                position: latLng,
                map: Gmaps.map.serviceObject,
                draggable: true
            });
            markersArray.push(marker);
            // Set and open infowindow
            var infowindow = new google.maps.InfoWindow({
                //content: '<h1>Your Gead</h1>'
            });
            infowindow.open(Gmaps.map.serviceObject,marker);
            // Listen to drag & drop
            google.maps.event.addListener(marker, 'dragend', function() {
                updateFormLocation(this.getPosition());
            });
        }
        // Removes the overlays from the map
        function clearOverlays() {
          if (markersArray) {
            for (var i = 0; i < markersArray.length; i++ ) {
              markersArray[i].setMap(null);
            }
          }
          markersArray.length = 0;
        }
    </script>
<% end %>

app/views/gadds/_list_gadds.html.erb
<ul class="users">
  <% @gadds.each do |gadd| %>
    <li>
      <%= link_to gadd.name, gadd %>
      <%= gadd.latitude %>
      <%= gadd.longitude %>
      <%= gadd.privacy %>
      <%= gadd.created_at %>
    </li>
  <% end %>
</ul>

app/views/gadds/_list_old.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>User</th>
    <th>Gmaps zoom</th>
	 <th>Privacy</th>

  </tr>

	<% @gadds.each do |gadd| %>
	  <tr>
		 <td><%= gadd.name %></td>
		 <td><%= gadd.latitude %></td>
		 <td><%= gadd.longitude %></td>
		  <td><%= gadd.gmaps_zoom %></td>
		<td><%= gadd.privacy %></td>
		 <td><%= link_to 'Destroy', gadd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  </tr>
	  <% end %>
	</table>

app/views/gadds/edit.html.erb
<h1>Editing gadd</h1>

<%= render 'form' %>

<%= link_to 'Show', @gadd %> |
<%= link_to 'Back', gadds_path %>

app/views/gadds/index.html.erb
<% provide(:title, 'views/gadds/index') %>


	<%= gmaps4rails(@json) %>
<%= render 'gmaps4rails_new' %>

<% if signed_in? %>

	<%= render 'form_create_gadd' %>

	<%= render 'list_gadds' %>

<% end %>

app/views/gadds/new.html.erb
<h1>New gadd</h1>

<%= render 'form' %>

<%= link_to 'Back', gadds_path %>

<%= render 'gmaps4rails_new' %>

app/views/gadds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gadd.name %>
</p>

<p>
  <b>Latitude:</b>
  <%= @gadd.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @gadd.longitude %>
</p>

<p>
  <b>GmapsZoom:</b>
  <%= @gadd.gmaps_zoom %>
</p>




<%= link_to 'Edit', edit_gadd_path(@gadd) %> |
<%= link_to 'Back', gadds_path %>

app/views/layouts/_footer.html.erb
  <footer>


	<small>
		MVP 0.1 | by GeoAddress
	</small>
	<nav>
	<ul>

	<li><a href="http://www.geoaddress.me/">News</a></li>
	</ul>
	</nav>

	<%= yield :scripts %>



  </footer>

app/views/layouts/_head.html.erb
  <head>
    <title>Geadd | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag "gmaps4rails" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
     <% if signed_in? %>

			<div class="nav pull-left">
         <%= form_tag gadds_path, :class => "form-inline",:method => "get" do %>
			  <%= text_field_tag :search, params[:search],:class=> "input-small",
			  						:style=> 'width: 400px' %>


			  <%= submit_tag("Filter", :name => nil, :class=> "input-small"	) %>
			</div>

			<% end %>

     <% end %>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">

                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<%= render 'layouts/head' %>


	<body>

		<%= render 'layouts/header' %>

		<div class="container">

		   <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
		   <%= yield %>



		<%= render 'layouts/footer' %>
		 </div>
	</body>



</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>